# Generated by Django 2.0.7 on 2018-08-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealcategory',
            options={'verbose_name_plural': 'Meal Categories'},
        ),
    ]
