# Generated by Django 2.0.7 on 2018-08-03 15:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180803_1706'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='meal',
            managers=[
                ('recipes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='mealrecipe',
            managers=[
            ],
        ),
    ]
