# Generated by Django 2.0.7 on 2018-08-04 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180803_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealrecipe',
            options={'verbose_name_plural': 'Meal Recipes'},
        ),
        migrations.AlterModelManagers(
            name='meal',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='mealrecipe',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealrecipe_recipes', to='core.Meal'),
        ),
    ]
