# Generated by Django 2.0.7 on 2018-08-04 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180804_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrecipe',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealrecipe_recipes', to='core.Meal'),
        ),
    ]
