# Generated by Django 2.0.7 on 2018-08-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180804_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrecipe',
            name='comments',
            field=models.ManyToManyField(related_name='mealrecipe_target', to='core.RecipeComment'),
        ),
    ]
