# Generated by Django 2.0.7 on 2018-08-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180804_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecomment',
            options={'verbose_name_plural': 'Recipe Comments'},
        ),
    ]
